/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.pages.profile": [],
    "filament.admin.resources.add-methods.index": [],
    "filament.admin.resources.adds.index": [],
    "filament.admin.resources.deposit-methods.index": [],
    "filament.admin.resources.deposits.index": [],
    "filament.admin.resources.kycs.index": [],
    "filament.admin.resources.landing-pages.index": [],
    "filament.admin.resources.landing-pages.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.money-requests.index": [],
    "filament.admin.resources.settings.index": [],
    "filament.admin.resources.settings.create": [],
    "filament.admin.resources.settings.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.transactions.index": [],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.withdraw-methods.index": [],
    "filament.admin.resources.withdraws.index": [],
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "upload.chunk.start": [],
    "upload.chunk.update": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.update.avatar": [],
    "profile.destroy": [],
    "active-status.update": [],
    "active-status.check": [
        {
            "name": "user",
            "required": false,
            "binding": "uuid"
        }
    ],
    "notification.mark-all-as-read": [],
    "notification.clear-all": [],
    "send-money.verify-password": [],
    "send-money.store": [],
    "wallet.deposit.index": [],
    "wallet.deposit.store": [],
    "wallet.check-balance": [
        {
            "name": "user",
            "required": false,
            "binding": "uuid"
        }
    ],
    "wallet.transactions.index": [],
    "wallet.withdraw.index": [],
    "wallet.withdraw.store": [],
    "kyc.store": [],
    "add.index": [],
    "add.create": [],
    "add.store": [],
    "add.show": [
        {
            "name": "add",
            "required": true,
            "binding": "uuid"
        }
    ],
    "add.edit": [
        {
            "name": "add",
            "required": true,
            "binding": "uuid"
        }
    ],
    "add.update": [
        {
            "name": "add",
            "required": true,
            "binding": "uuid"
        }
    ],
    "add.destroy": [
        {
            "name": "add",
            "required": true,
            "binding": "uuid"
        }
    ],
    "marketplace.index": [],
    "money.request": [],
    "money.accept": [
        {
            "name": "moneyRequest",
            "required": true,
            "binding": "uuid"
        }
    ],
    "money.cancel": [
        {
            "name": "moneyRequest",
            "required": true,
            "binding": "uuid"
        }
    ],
    "money.reject": [
        {
            "name": "moneyRequest",
            "required": true,
            "binding": "uuid"
        }
    ],
    "money.request-release": [
        {
            "name": "moneyRequest",
            "required": true,
            "binding": "uuid"
        }
    ],
    "money.release": [
        {
            "name": "moneyRequest",
            "required": true,
            "binding": "uuid"
        }
    ],
    "money.report": [
        {
            "name": "moneyRequest",
            "required": true,
            "binding": "uuid"
        }
    ],
    "referrals.index": [],
    "earnings.index": [],
    "earnings.convert": [
        {
            "name": "from_id",
            "required": true
        }
    ],
    "admin.login-as": [
        {
            "name": "user",
            "required": true,
            "binding": "uuid"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "chat.index": [],
    "chat.check-new-messages": [],
    "chat.user-chats": [],
    "chat.receiver-chat": [
        {
            "name": "receiver",
            "required": true,
            "binding": "uuid"
        }
    ],
    "chat.typing": [
        {
            "name": "chat",
            "required": true,
            "binding": "uuid"
        }
    ],
    "chat.show": [
        {
            "name": "chat",
            "required": true,
            "binding": "uuid"
        }
    ],
    "search-users": [],
    "messages": [],
    "messages.money-requests": [
        {
            "name": "chat",
            "required": true,
            "binding": "uuid"
        }
    ],
    "messages.check-new": [
        {
            "name": "chat",
            "required": true,
            "binding": "uuid"
        }
    ],
    "messages.get-new": [
        {
            "name": "chat",
            "required": true,
            "binding": "uuid"
        }
    ],
    "message.store": [
        {
            "name": "chat",
            "required": true,
            "binding": "uuid"
        }
    ],
    "helpline": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
