/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ApplicationLogo: typeof import('../Components/ApplicationLogo')['default']
  const AuthenticatedLayout: typeof import('../Layouts/AuthenticatedLayout')['default']
  const BaseLayout: typeof import('../Layouts/BaseLayout')['default']
  const Checkbox: typeof import('../Components/Checkbox')['default']
  const DangerButton: typeof import('../Components/DangerButton')['default']
  const Dropdown: typeof import('../Components/Dropdown')['default']
  const GuestLayout: typeof import('../Layouts/GuestLayout')['default']
  const Head: typeof import('../Components/Head')['default']
  const HugeiconsAlertCircle: typeof import('~icons/hugeicons/alert-circle.tsx')['default']
  const InputError: typeof import('../Components/InputError')['default']
  const InputLabel: typeof import('../Components/InputLabel')['default']
  const Modal: typeof import('../Components/Modal')['default']
  const NavLink: typeof import('../Components/NavLink')['default']
  const PrimaryButton: typeof import('../Components/PrimaryButton')['default']
  const ResponsiveNavLink: typeof import('../Components/ResponsiveNavLink')['default']
  const SecondaryButton: typeof import('../Components/SecondaryButton')['default']
  const TextInput: typeof import('../Components/TextInput')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
