/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ApplicationLogo: typeof import('../Components/ApplicationLogo')['default']
  const AuthenticatedLayout: typeof import('../Layouts/AuthenticatedLayout')['default']
  const BaseLayout: typeof import('../Layouts/BaseLayout')['default']
  const Checkbox: typeof import('../Components/Checkbox')['default']
  const DangerButton: typeof import('../Components/DangerButton')['default']
  const DashboarLayout: typeof import('../Layouts/DashboarLayout')['default']
  const Dropdown: typeof import('../Components/Dropdown')['default']
  const GuestLayout: typeof import('../Layouts/GuestLayout')['default']
  const Head: typeof import('../Components/Head')['default']
  const HeroiconsCurrencyBangladeshiSolid: typeof import('~icons/heroicons/currency-bangladeshi-solid.tsx')['default']
  const HeroiconsUser: typeof import('~icons/heroicons/user.tsx')['default']
  const HugeiconsBubbleChat: typeof import('~icons/hugeicons/bubble-chat.tsx')['default']
  const HugeiconsMenu02: typeof import('~icons/hugeicons/menu02.tsx')['default']
  const HugeiconsNotification03: typeof import('~icons/hugeicons/notification03.tsx')['default']
  const HugeiconsUserCircle: typeof import('~icons/hugeicons/user-circle.tsx')['default']
  const Input: typeof import('../Components/Input')['default']
  const InputError: typeof import('../Components/InputError')['default']
  const InputLabel: typeof import('../Components/InputLabel')['default']
  const MessageType: typeof import('./_generated')['MessageType']
  const Modal: typeof import('../Components/Modal')['default']
  const NavLink: typeof import('../Components/NavLink')['default']
  const Navbar: typeof import('../Components/Navbar')['default']
  const PrimaryButton: typeof import('../Components/PrimaryButton')['default']
  const ResponsiveNavLink: typeof import('../Components/ResponsiveNavLink')['default']
  const SecondaryButton: typeof import('../Components/SecondaryButton')['default']
  const Sidebar: typeof import('../Components/Chat/Sidebar')['default']
  const TextInput: typeof import('../Components/TextInput')['default']
  const Topbar: typeof import('../Components/Chat/Topbar')['default']
  const UserType: typeof import('./_generated')['UserType']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useAuth: typeof import('../Hooks/useAuth')['default']
  const useCallback: typeof import('react')['useCallback']
  const useConfig: typeof import('../Hooks/useConfig')['default']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MessageType, UserType } from './_generated'
  import('./_generated')
}
