export type Add = {
    id: any;
    uuid: string;
    type: string;
    owner_id: any;
    add_method_id: any;
    amount: any;
    rate: any;
    limit_max?: any;
    limit_min?: any;
    contact?: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
    add_method?: AddMethod;
    owner?: User;
};
export type AddMethod = {
    id: any;
    name: string;
    logo?: string;
    color?: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
export type Chat = {
    id: any;
    uuid: string;
    sender_id: any;
    receiver_id: any;
    typing?: string;
    is_read: any;
    is_notified: any;
    is_archived: any;
    is_pinned: any;
    created_at: string;
    updated_at?: string;
    last_message_at?: any;
    is_typing: any;
    from: any;
    created_at_human: any;
    updated_at_human: any;
    sender?: User;
    receiver?: User;
    messages?: Message[];
};
export type DepositMethod = {
    id: any;
    uuid: string;
    label: string;
    description?: string;
    logo: string;
    category: string;
    account_holder?: string;
    mode?: string;
    number?: string;
    secrets?: string;
    additional_fields?: string;
    metadata?: string;
    created_at: string;
    updated_at?: string;
    swift_code?: string;
    branch?: string;
    routing_number?: string;
    branch_name?: string;
    charge: any;
    is_fixed_amount: any;
    created_at_human: any;
    updated_at_human: any;
};
export type Earning = {
    id: any;
    user_id: any;
    from_id?: any;
    amount: any;
    currency: string;
    status: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
    user?: User;
    from?: User;
};
export type Kyc = {
    id: any;
    uuid: string;
    user_id: any;
    doc_type: string;
    front_image: string;
    back_image: string;
    approved_at?: any;
    rejected_at?: any;
    created_at: string;
    updated_at?: string;
    status: any;
    created_at_human: any;
    updated_at_human: any;
    user?: User;
};
export type KycController = {
    created_at_human: any;
    updated_at_human: any;
};
export type LandingPage = {
    id: any;
    hero?: string;
    payment_methods?: string;
    how_it_works?: string;
    socials?: string;
    about?: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
export type Message = {
    id: any;
    uuid: string;
    chat_id: any;
    sender_id: any;
    receiver_id: any;
    type: string;
    body: string;
    is_read: any;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
    sender?: User;
    receiver?: User;
    chat?: Chat;
    money_request?: MoneyRequest;
};
export type Model = {
    created_at_human: any;
    updated_at_human: any;
};
export type MoneyRequest = {
    id: any;
    uuid: string;
    sender_id: any;
    receiver_id: any;
    message_id?: any;
    amount: any;
    currency: string;
    accepted_at?: string;
    released_at?: string;
    rejected_at?: string;
    note?: string;
    created_at: string;
    updated_at?: string;
    release_requested_at?: string;
    cancelled_at?: string;
    status: any;
    created_at_human: any;
    updated_at_human: any;
    sender?: User;
    transaction?: Wallet;
    receiver?: User;
    message?: Message;
    chat?: Chat;
    from?: User;
};
export type PhoneHistory = {
    id: any;
    user_id: any;
    phone: string;
    created_at?: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
export type Setting = {
    id: any;
    transactions?: string;
    general?: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
export type User = {
    id: any;
    uuid: string;
    name: string;
    avatar?: string;
    phone?: string;
    email: string;
    date_of_birth?: string;
    gender?: string;
    country?: string;
    address?: string;
    email_verified_at?: string;
    type: string;
    referral_id?: string;
    created_at?: string;
    updated_at?: string;
    last_seen_at?: any;
    referred_by?: any;
    kyc_status: string;
    balance: any;
    referrals?: User[];
    phone_history?: PhoneHistory[];
    referer?: User;
    kyc?: Kyc;
};
export type Wallet = {
    id: any;
    uuid: string;
    owner_id: any;
    transaction_id?: string;
    transaction_type: string;
    type: string;
    amount: any;
    commission: any;
    currency: string;
    note?: string;
    method?: string;
    payment_number?: string;
    approved_at?: string;
    cancelled_at?: string;
    failed_at?: string;
    created_at: string;
    updated_at?: string;
    additional_fields?: string;
    receipt?: string;
    deposit_method_id?: any;
    withdraw_method_id?: any;
    account_holder?: string;
    user_id?: any;
    money_request_id?: any;
    status: any;
    created_at_human: any;
    updated_at_human: any;
    withdraw_method?: WithdrawMethod;
    user?: User;
    sender?: User;
    receiver?: User;
    deposit_method?: DepositMethod;
    owner?: User;
};
export type WithdrawMethod = {
    id: any;
    uuid: string;
    label: string;
    description?: string;
    logo: string;
    category: string;
    fields?: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
