export type Chat = {
    id: any;
    uuid: string;
    sender_id: any;
    receiver_id: any;
    typing?: string;
    is_read: any;
    is_notified: any;
    is_archived: any;
    is_pinned: any;
    created_at: string;
    updated_at?: string;
    is_typing: any;
    from: any;
    created_at_human: any;
    updated_at_human: any;
    sender?: User;
    receiver?: User;
    messages?: Message[];
};
export type Message = {
    id: any;
    uuid: string;
    chat_id: any;
    sender_id: any;
    receiver_id: any;
    type: string;
    body: string;
    is_read: any;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
    sender?: User;
    receiver?: User;
    chat?: Chat;
};
export type Model = {
    created_at_human: any;
    updated_at_human: any;
};
export type MoneyRequest = {
    id: any;
    uuid: string;
    sender_id: any;
    receiver_id: any;
    message_id?: any;
    amount: any;
    currency: string;
    accepted_at?: any;
    released_at?: any;
    rejected_at?: any;
    note?: string;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
export type User = {
    id: any;
    uuid: string;
    name: string;
    username: string;
    avatar?: string;
    phone?: string;
    email: string;
    email_verified_at?: string;
    type: string;
    referral_id?: string;
    created_at?: string;
    updated_at?: string;
};
export type Wallet = {
    id: any;
    uuid: string;
    user_id: any;
    type: string;
    remark: string;
    amount: any;
    currency: string;
    completed_at?: any;
    approved_at?: any;
    failed_at?: any;
    created_at: string;
    updated_at?: string;
    created_at_human: any;
    updated_at_human: any;
};
