name: Staging
on:
  push:
    branches: ["staging"]

jobs:
  Deploying:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: SSH to cPanel and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          port: ${{ secrets.port }}
          command_timeout: 30m
          script: |
            # set -e  # Exit on any error

            # Step 1: Install Node.js using NVM if not already installed
            if ! command -v npm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
              source ~/.nvm/nvm.sh
              nvm install --lts
              source ~/.bashrc
            fi

            # Step 2: Change to project directory
            cd public_html/dev.paykaa.com

            # Step 3: Git setup
            if [ ! -d .git ]; then
              git clone git@github.com:itsemon245/paykaa.git .
            else
              git fetch origin
            fi

            # Step 4: Handle local changes, switch to the correct branch, and pull updates
            git reset --hard
            git clean -fd
            git checkout staging
            git pull origin staging

            # Step 5: Install Node.js dependencies and build assets
            npm ci  # Faster than npm install, as it uses lockfile
            npm run build

            # Step 6: Clean up Node.js modules to save space
            rm -rf node_modules

            # Step 7: Update Composer dependencies and optimize Laravel
            composer install --optimize-autoloader --no-dev
            php artisan optimize:clear
            php artisan optimize

            # Step 8: Run migrations
            php artisan migrate --force

            # Step 9: Recreate storage symlink
            rm -rf public/storage public/temp
            php artisan storage:link
